const products = [
    {
        _id: '1',
        name: 'NCT Lightstick',
        image: '/images/p1.jpg',
        description: 'SM Entertainment Boy group NCT lightstick Version 1',
        brand:'SM',
        category:'Kpop',
        price: 25.00,
        countInStock: 15,
        rating: 5,
        numReviews: 23,
    },
    {
        _id: '2',
        name: 'ATEEZ Lightstick',
        image: '/images/p2.jpg',
        description: 'KQ Entertainment ATEEZ Official Lightstick Version 1',
        brand:'KQ',
        category:'Kpop',
        price: 35.00,
        countInStock: 5,
        rating: 4.5,
        numReviews: 8,
    },
    {
        _id: '3',
        name: 'SEVENTEEN Lightstick',
        image: '/images/p3.jpg',
        description: 'Pledis Entertainment Official Lightstick Version 2',
        brand:'Pledis',
        category:'Kpop',
        price: 40.00,
        countInStock: 10,
        rating: 4.5,
        numReviews: 13,
    },
    {
        _id: '4',
        name: 'EXO Lightstick',
        image: '/images/p4.jpg',
        description: 'SM Entertainment EXO Official Lightstick Version 3',
        brand:'SM',
        category:'Kpop',
        price: 45.00,
        countInStock: 10,
        rating: 4.5,
        numReviews: 9,
    },
    {
        _id: '5',
        name: 'CIX Lightstick',
        image: '/images/p5.jpg',
        description: 'C9 Entertainment CIX Official Lighstick',
        brand:'C9',
        category:'Kpop',
        price: 20.00,
        countInStock: 5,
        rating: 4,
        numReviews: 4,
    },
    {
        _id: '6',
        name: 'TWICE Lightstick',
        image: '/images/p6.jpg',
        description: 'JYP Entertainment Girl group Twice Official Lightstick Version 2',
        brand:'JYP',
        category:'Kpop',
        price: 35.00,
        countInStock: 13,
        rating: 5,
        numReviews: 9,
    },
    {
        _id: '7',
        name: 'RED VELVET Lightstick',
        image: '/images/p7.jpg',
        description: 'SM Entertainment Girl group Official Lightstick',
        brand:'adasd',
        category:'Kpop',
        price: 40.00,
        countInStock: 5,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '8',
        name: 'BLACKPINK Lightstick',
        image: '/images/p8.jpg',
        description: 'YG Entertainment Blackpink Official Lightstick Version 2',
        brand:'YG',
        category:'Kpop',
        price: 30.00,
        countInStock: 7,
        rating: 4.5,
        numReviews: 12,
    },

]
export default products